### ISSUE TITLE
Feature Request:  Modded BIOS with Stock Voltages download option

### ISSUE THREAD

**Issue by rtiangha** [Thiblizz/l502x-modded-bios#2]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Please add a "modded bios with stock voltages" download option for those whose hardware doesn't properly run with the lower voltage mod, even when running at stock clock speeds.

**Current behaviour:**

Sometimes (not always, but often enough to get annoying) I get a blue screen whenever trying to do something that involves using the NVIDIA GPU on Windows 10 when running the Modded BIOS with the lower voltages (it also did it with Kasar's custom BIOS with the lower voltages, but *not* with his modded bios with stock voltages). And I've never had an issue running Dell's stock BIOS either. I suspect my hardware just isn't good enough to reliably run at stock clock speeds with the lower voltages, so a modded bios option with stock voltages would be greatly appreciated as the feature set still works as expected on both Windows 10 and Linux (technically, Qubes OS, although I primarily use the Intel video card on that and I don't think it ever accesses the NVIDIA card).

**Expected behaviour:**

No blue-screens doing normal tasks!

**Steps to reproduce the problem:**

1. Flash modded bios with lower voltages on my hardware (either this BIOS or Captain Kasar's versions) with stock clock speeds.
2. Try to do something with the NVIDIA video card (ex. watch movie, play game, etc).
3. Blue screen (sometimes).

**Branch(es):**

Master

**Modded BIOS version:** Happens under 1.01 and 1.03 (I never flashed 1.02)

**GPU model:** Geforce 540m on a DELL XPS 15 L502X

**Display driver version:** NVIDIA 378.92

**Operating system:** Windows 10 Pro 64-bit

**Any related software which may cause the BIOS to act strangely:**

Anything that tries to access the NVIDIA GPU in Windows 10, but other than that, the occurrence appears to be random.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If you are fixing a bug for an existing feature or want to make a change, create a Pull Request.)

**Comment by Thiblizz** [comment]
Thanks for your input.

In the next release, I will remove the original Dell BIOS, and thus only offer to flash the modded BIOS (the current one with lowered voltage and a "stock" one with voltage untouched.

Of course for people who want to revert back the original Dell BIOS, they will still be able to dowload it on Dell's website, but as it contains security/privacy issues (like the Computrace's Rootkit), I don't want to support it anymore.

**Comment by Thiblizz** [comment]
Original request done in 6bbfaedab53437f923ba71a743b6996bb6cdb792.
