### ISSUE TITLE
Freeze when move to either security or exit tab

### ISSUE THREAD

**Issue by jasonhjia** [Thiblizz/l502x-modded-bios#3]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Freeze when move to either security or exit tab.

**Current behaviour:**

After flash, it was working fine for a while, but soon I got freeze in bios setting quite often. Either I press right arrow key to Security tab, or I press left arrow key to Exit, it 100% freeze.

So this leaves me only navigate in Main and Advanced tab, and after change, press Esc to Exit tab and Exit Saving Changes. I don't know what is the root cause.

**Expected behaviour:**

Should allow user navigate in all tabs without problem

**Steps to reproduce the problem:**

1. Boot the machine
2. Press F2 to enter setup
3. Use either 

**Branch(es):**

master

**BIOS edition:** Stock BIOS v1.0.0

**GPU model:** 525M

**Display driver version:** N/A

**Operating system:** N/A

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If you are fixing a bug for an existing feature or want to make a change, create a Pull Request.)

**Comment by Thiblizz** [comment]
Hello,

I will try to reproduce it, but I do not remember having this issue.

Do you have the same issue with the **Undervolted BIOS**?

**Comment by jasonhjia** [comment]
I didn't try Undervolted bios, but my machine is working fine with both windows and ubuntu. I will try memtest when i get time.

**Comment by jasonhjia** [comment]
After install the Undervolted bios, the problem resolved. Thx!
